spring:
  application:
    name: journalBuddy
  profiles:
    active: private

  data:
    mongodb:
      uri: <MONGO_URI>
      database: <MONGO_DB>
      auto-index-creation: true

  security:
    user:
      name: <APP_USER>
      password: <APP_PASS>

